version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:15"
      timezone: "America/Chicago"
    commit-message:
      prefix: "🤖 "
    cooldown:
      default-days: 3
    groups:
      oxc:
        patterns:
          - "oxfmt"
          - "oxlint"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "09:15"
      timezone: "America/Chicago"
    commit-message:
      prefix: "🤖 "
    cooldown:
      default-days: 3
