version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    commit-message:
      prefix: "🤖 "
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint*"
    cooldown:
      default-days: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "11:00"
    commit-message:
      prefix: "🤖 "
    cooldown:
      default-days: 3
